services:
    postgres:
        image: postgres:latest
        container_name: postgres_denodo
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - postgres_network
    pgadmin4:
        image: dpage/pgadmin4:latest
        container_name: pgadmin4_denodo
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_USER: admin
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        depends_on:
            - postgres
        networks:
            - postgres_network

networks:
  postgres_network:
    driver: bridge
volumes:
  pgdata: