name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Cancel previous workflows
      uses: fkirc/skip-duplicate-actions@master
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Clean and build with Maven
      id: packaging-jar
      shell: bash
      run: mvn clean install
